Refactor/eos 10979 refactoring credentials
Stratio/kind pull request #46
Opened 2023-02-21 16:34 UTC by lreciomelero

2023-02-24 09:51 UTC, stg-0 requested changes

2023-02-24 09:51 UTC, stg-0 commented on pkg/cluster/internal/create/actions/cluster/cluster.go
> +	DockerRegistries []ExternalRegistryCredentials `yaml:"docker_registries"`
```suggestion
	GithubToken      string                        `yaml:"github_token"`
	DockerRegistries []DockerRegistryCredentials `yaml:"docker_registries"`
```

2023-02-24 09:51 UTC, stg-0 commented on pkg/cluster/internal/create/actions/cluster/cluster.go
> +type ExternalRegistryCredentials struct {
```suggestion
type DockerRegistryCredentials struct {
```

2023-03-06 09:40 UTC, kahun commented on pkg/cluster/internal/create/actions/createworker/createworker.go
> +
Shall we remove these block comments?

2023-03-06 12:55 UTC, kahun approved these changes
LGTM

2023-03-06 14:59 UTC, lreciomelero commented on pkg/cluster/internal/create/actions/cluster/cluster.go
> +	DockerRegistries []ExternalRegistryCredentials `yaml:"docker_registries"`
resolved

2023-03-06 14:59 UTC, lreciomelero commented on pkg/cluster/internal/create/actions/cluster/cluster.go
> +type ExternalRegistryCredentials struct {
resolved

2023-03-06 15:10 UTC, merged