doc: add mention of scaling from zero
Stratio/kind pull request #523
Opened 2024-03-18 14:06 UTC by esierra-stratio

2024-03-18 14:20 UTC, stratiocommit commented
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/ROOT/pages/installation.adoc

2024-03-18 14:26 UTC, stratiocommit commented
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/ROOT/pages/installation.adoc

2024-03-20 08:58 UTC, iamjanr commented on stratio-docs/es/modules/ROOT/pages/installation.adoc
> +|_max++_++size_/_min++_++size**_
Quizas sustituiría los "**" por una "Nota".

2024-03-20 09:41 UTC, stg-0 commented on stratio-docs/es/modules/ROOT/pages/installation.adoc
> +
```suggestion
NOTE: Se ha implementado la opción de establecer un min_size igual a cero, lo que permite que el autoscalado pueda incrementar o disminuir el número de nodos hasta alcanzar cero según sea necesario. Esta funcionalidad facilita un ahorro significativo de costos en comparación con versiones anteriores, ya que posibilita la definición de un grupo de workers sin instanciar ningún recurso en el _cloud provider_ que no sea necesario.

```

2024-03-20 09:41 UTC, stg-0 commented on stratio-docs/es/modules/ROOT/pages/installation.adoc
> +|_max++_++size_/_min++_++size**_
```suggestion
|_max++_++size_/_min++_++size_
```

2024-03-20 09:44 UTC, stratiocommit commented
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/ROOT/pages/installation.adoc

2024-03-20 09:57 UTC, stg-0 approved these changes
LGTM

2024-03-21 11:25 UTC, stratiocommit commented
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/ROOT/pages/installation.adoc

2024-03-25 09:53 UTC, tperez-stratio requested changes
@esierra-stratio te devuelvo un par de cambios. Por otro lado, para poder subir la versión en inglés necesito que me des permisos de escritura a tu repositorio remoto ya que ahora mismo no puedo hacer commits sobre tu PR. ¡Gracias!

2024-03-25 09:53 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/installation.adoc
> +NOTE: Se ha implementado la opción de establecer un min_size igual a cero, lo que permite que el autoscalado pueda incrementar o disminuir el número de nodos hasta alcanzar cero según sea necesario.
```suggestion
NOTE: Se ha implementado la opción de establecer un _min++_++size_ igual a cero, lo que permite que el autoescalado pueda incrementar o disminuir el número de nodos hasta alcanzar cero según sea necesario. Esta funcionalidad proporciona un ahorro significativo de costes en comparación con versiones anteriores ya que permite la definición de un grupo de _workers_ sin instanciar ningún recurso en el proveedor _cloud_ que no sea necesario.
```

2024-03-25 09:53 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/installation.adoc
> +Para garantizar una configuración adecuada de _aws-load-balancer-controller-manager_ (no habilitado por defecto en entornos gestionados, EKS) es fundamental seguir una serie de pasos en los que se in
```suggestion
Para garantizar una configuración adecuada de _aws-load-balancer-controller-manager_ (no habilitado por defecto en entornos gestionados, EKS) es fundamental seguir una serie de pasos en los que se incluye la integración con https://docs.aws.amazon.com/es_es/eks/latest/userguide/iam-roles-for-service-accounts.html[IRSA].
```

2024-03-25 14:31 UTC, tperez-stratio approved these changes

2024-03-25 14:36 UTC, merged