Added ClusterConfig docs
Stratio/kind pull request #524
Opened 2024-03-18 15:42 UTC by lreciomelero

2024-03-19 10:01 UTC, stratiocommit commented
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/ROOT/pages/architecture.adoc

2024-03-20 08:40 UTC, iamjanr commented on stratio-docs/es/modules/ROOT/pages/clusterconfig-reference.adoc
> +| Campo | Descripción | Predeterminado | Validación
Separar el type del field

2024-03-20 08:41 UTC, iamjanr commented on stratio-docs/es/modules/ROOT/pages/clusterconfig-reference.adoc
> +| Campo | Descripción | Predeterminado | Validación
Separar el type del field

2024-03-20 08:41 UTC, iamjanr commented on stratio-docs/es/modules/ROOT/pages/clusterconfig-reference.adoc
> +ControlplaneConfig define las configuraciones para el controlplane
Separar el type del field

2024-03-20 08:41 UTC, iamjanr commented on stratio-docs/es/modules/ROOT/pages/clusterconfig-reference.adoc
> +| Campo | Descripción | Predeterminado | Validación
Separar el type del field

2024-03-20 08:46 UTC, iamjanr commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +Es posible consultar su API Reference en [blue]_clusterconfig-reference.adoc_
Creo k lo de [blue] se puede quitarya que "no veo k lo resalte"
Añadir un link al fichero

2024-03-20 08:47 UTC, iamjanr commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +Por defecto, se instalará la última versión del chart disponible en el repositorio de helm indicado en el objeto KeosCluster, aunque este comportamiento se puede sobrescribir e indicar la versión que
Quitar [Blue] , ñadir link y especificar cual es el valor.

2024-03-20 08:50 UTC, iamjanr reviewed
Quizas deberíamos actualizar los "Ejemplo de descriptor" en el doc "Installation.adoc" adicionando el "Clucterconfig"

2024-03-20 10:20 UTC, stg-0 commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +
```suggestion
== Objeto _ClusterConfig_

Del mismo modo que el Objeto _KeosCluster_, durante la fase de instalación se creará el recurso *ClusterConfig* que permite indicar configuraciones específicas para ese _cluster_ en particular.

La declaración de este recurso de Kubernetes deberá hacerse en el propio fichero descriptor, junto al objeto KeosCluster. En caso de no indicarse el recurso ClusterConfig durante la instalación del _cluster_, se generará el recurso con los valores por defecto.

Para mas detalles, se puede consultar el xref:attachment$clusterconfig-reference.adoc[API Reference].

=== Elección del Cluster Operator

Por defecto, se instalará la última versión del chart disponible en el repositorio de helm indicado en el objeto KeosCluster, aunque este comportamiento se puede sobrescribir e indicar la versión que queramos instalar, indicando el valor de [blue]_clusterconfig-reference.adoc_.

Para la elección de la última versión disponible, se tiene en cuenta tanto el orden de precedencia del versionado como la ordenación alfanumérica de las versiones. Es decir, se dará prioridad a las versiones en el siguiente orden: _release_, _prerrelease_, _milestone_, _snapshots_ y _pull_request_. 

En caso de que coincidan en un mismo repositorio varias versiones de la misma precedencia (exceptuando prerreleases), se devolverá la última versión alfanuméricamente ordenada. De este modo, se devolverá antes, por ejemplo, la versión 0.2.1 a la versión 0.2.0.

Existe una excepción a este mecanismo de elección. Debido al _naming_ de versionado en _Stratio_, si las versiones existentes de mayor precedencia son _prereleases_, al no poder establecer el orden de forma alfanumérica se devolverá la última versión subida al repositorio de helm.

NOTA: En caso de optar por la elección por defecto del chart, no será necesario indicar el campo durante la instalación, pero sí se verá reflejado este campo cuando el objeto se cree en el cluster con la versión que se ha recuperado.

```

2024-03-20 10:39 UTC, stg-0 commented on stratio-docs/es/modules/ROOT/pages/clusterconfig-reference.adoc
> +|===
```suggestion
= Referencia API

== _ClusterConfig_

Este objeto de Kubernetes permite definir las distintas configuraciones para el _keoscluster_ junto al que se crea.

[cols="20a,50a,15a,15a", options="header"]
|===
| Parámetro | Descripción | Default | Validación

| *`metadata`* https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#objectmeta-v1-meta[ObjectMeta]
| Consulta la documentación de la API de Kubernetes para conocer los campos de _metadata_.
| -
| -

| *`spec`* _ClusterConfigSpec_
| -
| -
| -

| *`status`* _ClusterConfigStatus_
| -
| -
| -
|===

=== _ClusterConfigSpec_

Este objeto define el estado deseado de _ClusterConfig_.

[cols="20a,50a,15a,15a", options="header"]
|===
| Parámetro | Descripción | Default | Validación

| *`eks_lb_controller`* _boolean_
| Permite instalar el operador `aws-load-balancer-controller-manager`.
| _false_
| -

| *`private_registry`* _boolean_
| Permite especificar el tipo de instalación. En caso de habilitarse este campo, las imágenes que deban descargarse durante el proceso de instalación del _cluster_ se recuperarán del _registry_ indicado como _keos++_++registry_.
| _false_
| -

| *`controlplane_config`* _ControlplaneConfig_
| Permite indicar las distintas configuraciones para el _control-plane_.
| -
| -

| *`workers_config`* _WorkersConfig_
| Permite indicar las distintas configuraciones para los nodos _workers_.
| -
| -

| *`cluster_operator_version`* _string_
| Permite especificar la versión del _chart_ del _cluster operator_ que se descargará desde el repositorio de Helm indicado en el _keoscluster_. Por defecto, se descarga la última versión presente en el repositorio de Helm.
| -
| -

| *`cluster_operator_image_version`* _string_
| Permite sobrescribir la versión de la imagen que se desplegará junto al _chart_. Por defecto, se instala la versión indicada en el fichero _values_ del _chart_, pero con este campo se puede sobrescribir la versión predeterminada.
| -
| -
|===

=== _ClusterConfigStatus_

Define el estado observado de _ClusterConfig_.

== _ControlplaneConfig_

Define las configuraciones para el _control-plane_.

[cols="20a,50a,15a,15a", options="header"]
|===
| Parámetro | Descripción | Default | Validación

| *`max_unhealthy`* _integer_
| Permite especificar el porcentaje máximo de máquinas del _control-plane_ que pueden encontrarse en estado _unhealthy_ antes de comenzar la reparación.
| 34
| Máximo: 100. Mínimo: 0.
|===

== _WorkersConfig_

Define las configuraciones para los nodos _workers_.

[cols="20a,50a,15a,15a", options="header"]
|===
| Parámetro | Descripción | Default | Validación

| *`max_unhealthy`* _integer_
| Permite especificar el porcentaje máximo de máquinas de un grupo de nodos _workers_ que pueden encontrarse en estado _unhealthy_ antes de comenzar la reparación.
| 34
| Máximo: 100. Mínimo: 0.
|===
```

2024-03-21 20:54 UTC, tperez-stratio requested changes
@lreciomelero te devuelvo algunos cambios tras la revisión y un comentario sobre la ubicación del fichero "clusterconfig-reference.adoc". Aplícalos si estás conforme y consúltame cualquier duda. Pide de nuevo una revisión cuando esté lista y me pondré con la versión en inglés. ¡Gracias!

2024-03-21 20:54 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/clusterconfig-reference.adoc
> +| Parámetro | Descripción | Default | Validación
```suggestion
| Parámetro | Descripción | Valor por defecto | Validación
```

2024-03-21 20:54 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +Del mismo modo que el Objeto _KeosCluster_, durante la fase de instalación se creará el recurso *ClusterConfig* que permite indicar configuraciones específicas para ese _cluster_ en particular.
```suggestion
Del mismo modo que el objeto _KeosCluster_, durante la fase de instalación se creará el recurso _ClusterConfig_, que permite indicar configuraciones específicas para ese _cluster_ en particular.
```

2024-03-21 20:54 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +La declaración de este recurso de Kubernetes deberá hacerse en el propio fichero descriptor, junto al objeto KeosCluster. En caso de no indicarse el recurso ClusterConfig durante la instalación del _
```suggestion
La declaración de este recurso de Kubernetes deberá hacerse en el propio fichero descriptor, junto al objeto _KeosCluster_. En caso de no indicarse durante la instalación del _cluster_, se generará el recurso con los valores por defecto.
```

2024-03-21 20:54 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +Para mas detalles, se puede consultar el xref:attachment$clusterconfig-reference.adoc[API Reference].
```suggestion
TIP: Para más detalles, consulta el documento de xref:attachment$clusterconfig-reference.adoc[referencia API].
```

2024-03-21 20:54 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +=== Elección del Cluster Operator
```suggestion
=== Elección del _Cluster Operator_
```

2024-03-21 20:54 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +Por defecto, se instalará la última versión del chart disponible en el repositorio de helm indicado en el objeto KeosCluster, aunque este comportamiento se puede sobrescribir e indicar la versión que
Creo que la página "clusterconfig-reference.adoc" no está bien ubicada dentro de ROOT. En mi opinión es una página de configuración que debería estar a un nivel un poco más profundo (anidada dentro de alguna sección o formando parte de la guía de operaciones). Lo comentamos por el chat o en una reunión si quieres.
```suggestion
Por defecto, se instalará la última versión del _chart_ disponible en el repositorio de Helm indicado en el objeto _KeosCluster_, aunque este comportamiento se puede sobrescribir e indicar la versión que se quiere instalar indicando el valor en la xref::clusterconfig-reference.adoc[configuración del _ClusterConfig_].
```

2024-03-21 20:54 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +Para la elección de la última versión disponible, se tiene en cuenta tanto el orden de precedencia del versionado como la ordenación alfanumérica de las versiones. Es decir, se dará prioridad a las v
```suggestion
Para la elección de la última versión disponible se tiene en cuenta tanto el orden de precedencia del versionado como la ordenación alfanumérica de las versiones. Es decir, se dará prioridad a las versiones en el siguiente orden: _release_, _prerrelease_, _milestone_, _snapshot_ y _pull++_++request_. 
```

2024-03-21 20:54 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +En caso de que coincidan en un mismo repositorio varias versiones de la misma precedencia (exceptuando prerreleases), se devolverá la última versión alfanuméricamente ordenada. De este modo, se devol
```suggestion
En caso de que coincidan en un mismo repositorio varias versiones de la misma precedencia (exceptuando _prerreleases_), se devolverá la última versión alfanuméricamente ordenada. De este modo, se devolverá antes, por ejemplo, la versión 0.2.1 a la versión 0.2.0.
```

2024-03-21 20:54 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +Existe una excepción a este mecanismo de elección. Debido al _naming_ de versionado en _Stratio_, si las versiones existentes de mayor precedencia son _prereleases_, al no poder establecer el orden d
```suggestion
Existe una excepción a este mecanismo de elección. Debido al _naming_ de versionado en Stratio, si las versiones existentes de mayor precedencia son _prerreleases_, al no poder establecer el orden de forma alfanumérica se devolverá la última versión subida al repositorio de Helm.
```

2024-03-21 20:54 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +NOTE: En caso de optar por la elección por defecto del chart, no será necesario indicar el campo durante la instalación, pero sí se verá reflejado este campo cuando el objeto se cree en el cluster co
```suggestion
NOTE: En caso de optar por la elección por defecto del _chart_, no será necesario indicar el campo durante la instalación pero sí se verá reflejado este campo cuando el objeto se cree en el _cluster_ con la versión que se ha recuperado.
```

2024-03-21 20:54 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/clusterconfig-reference.adoc
> +| Parámetro | Descripción | Default | Validación
```suggestion
| Parámetro | Descripción | Valor por defecto | Validación
```

2024-03-21 20:54 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/clusterconfig-reference.adoc
> +| Permite sobrescribir la versión de la imagen que se desplegará junto al _chart_. Por defecto, se instala la versión indicada en el fichero _values_ del _chart_, pero con este campo se puede sobresc
```suggestion
| Permite sobrescribir la versión de la imagen que se desplegará junto al _chart_. Por defecto, se instala la versión indicada en el fichero _values.yaml_ del _chart_, pero con este campo se puede sobrescribir la versión predeterminada.
```

2024-03-21 20:54 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/clusterconfig-reference.adoc
> +| Parámetro | Descripción | Default | Validación
```suggestion
| Parámetro | Descripción | Valor por defecto | Validación
```

2024-03-21 20:54 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/clusterconfig-reference.adoc
> +| Parámetro | Descripción | Default | Validación
```suggestion
| Parámetro | Descripción | Valor por defecto | Validación
```

2024-03-25 14:21 UTC, merged