[CLOUD-255] Docs/cloud 255 support oci repos
Stratio/kind pull request #525
Opened 2024-03-19 11:04 UTC by lreciomelero

2024-03-19 11:07 UTC, stratiocommit commented
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/ROOT/pages/architecture.adoc
EN - modules/ROOT/pages/installation.adoc

2024-03-20 08:55 UTC, iamjanr approved these changes
LGTM

2024-03-20 09:48 UTC, stg-0 commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +NOTE: Las url de los repositorios de tipo OCI llevan el prefijo *oci://*. Por ejemplo, oci://stratioregistry.azurecr.io/helm-repository-example
```suggestion
|===

== Helm Repository

Como prerrequisito de la instalación se debe indicar un repositorio de helm del que se pueda extraer el chart de _Cluster Operator_. Este repositorio puede utilizar protocolo https u oci (utilizado para repositorios de _cloud providers_ como ECR, GAR o ACR).

[.center,cols="2,1",width=40%]
|===
^|AWS
^|ecr, generic

^|EKS
^|ecr, generic

^|GCP
^|gar, gcr, generic

^|Azure
^|acr, generic

^|AKS
^|acr, generic
|===

NOTE: Las url de los repositorios de tipo OCI llevan el prefijo *oci://*. Por ejemplo, oci://stratioregistry.azurecr.io/helm-repository-example.

NOTE: Verificar en la documentación de keos-installer los repositorios que se soporten en la versión a utilizar.
```

2024-03-20 09:56 UTC, stg-0 commented on stratio-docs/es/modules/ROOT/pages/installation.adoc
> +
```suggestion
=== Helm Repository

Como prerrequisito de instalación, se debe indicar el repositorio helm del que se descargará el chart de helm del _Cluster Operator_. Este apartado permite indicar la url del repositorio, su tipo y si se trata de un repositorio autenticado.

[cols="1,4,2,1"]
|===
^|Nombre ^|Descripción ^|Ejemplo ^|Opcional

|_auth++_++required_
|Indica si el repositorio es autenticado
|false
|Si, default: false.

|_url_
|Url del repositorio
|*Repositorios OCI*: oci://stratioregistry.azurecr.io/helm-repository-example + 
*Repositorios HTTPS*: https://[IP]:8080
|No

|_type_
|Tipo del repositorio
|generic o ecr
|Si, default: generic

|===

NOTE: Los repositorios OCI (de _cloud providers_ como ECR, GAR o ACR) nunca son autenticados. La autenticación se realizará mediante las credenciales utilizadas en el aprovisionamiento. Verificar en la documentación de keos-installer los repositorios que se soporten en la versión a utilizar.

```

2024-03-20 10:00 UTC, stratiocommit commented
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/ROOT/pages/architecture.adoc
EN - modules/ROOT/pages/installation.adoc

2024-03-21 10:49 UTC, stg-0 approved these changes
lgtm

2024-03-22 12:00 UTC, tperez-stratio requested changes
@lreciomelero te paso unos cambios. Revisa y aplica si estás conforme. Pide una nueva revisión cuando esté lista para ponerme con la versión en inglés. ¡Gracias!

2024-03-22 12:00 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/installation.adoc
> +|Si, default: false.
```suggestion
| _auth++_++required_
| Indica si el repositorio es autenticado.
| _false_
| Sí. Por defecto: _false_.
```

2024-03-22 12:00 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/installation.adoc
> +|No
```suggestion
| _url_
| URL del repositorio.
| *Repositorios OCI*: oci://stratioregistry.azurecr.io/helm-repository-example + 
*Repositorios HTTPS*: https://[IP]:8080
| No
```

2024-03-22 12:00 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/installation.adoc
> +|===
```suggestion
| _type_
| Tipo del repositorio.
| _generic_ o ecr.
| Sí. Por defecto: _generic_.
|===
```

2024-03-22 12:00 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/installation.adoc
> +NOTE: Los repositorios OCI (de _cloud providers_ como ECR, GAR o ACR) nunca son autenticados. La autenticación se realizará mediante las credenciales utilizadas en el aprovisionamiento. Verificar en
```suggestion
NOTE: Los repositorios OCI (de proveedores _cloud_ como ECR, GAR o ACR) nunca son autenticados. La autenticación se realizará mediante las credenciales utilizadas en el aprovisionamiento. Por favor, verifica en la documentación de _Stratio KEOS_ los repositorios que se soportan en la versión a utilizar.
```

2024-03-25 15:54 UTC, tperez-stratio approved these changes
@lreciomelero he añadido la versión en inglés. Si ves todo OK mergea. Gracias.

2024-03-25 16:58 UTC, merged