Stratio docs Update
Stratio/kind pull request #560
Opened 2024-06-11 08:55 UTC by iamjanr

## Description

Update stratio-docs docuemntation

## Related Pull Requests

N/A

## Pull Request Checklist:

- [ ] [PR title] Include a title referencing a ticket in Jira (e.g. "[CLOUDS-99] Implement a new funcionality").
- [ ] [PR desc] Add a summary of the changes made in simple terms.
- [ ] [PR desc] List any pull-request related to this change (docs, tests, feature, etc.).
- [X] [PR labels] Add the corresponding labels (release, skips, cherry-pick, AT-eks-smoke, etc).
- [ ] [Docs] Are changes to the documentation required? (if so, please add references to those PRs).
- [ ] [QA] Are new unit tests required according with the changes? (if so, please add references to those PRs).

2024-06-12 09:43 UTC, tperez-stratio requested changes
@iamjanr te devuelvo un par de traducciones. Ojo que se te ha olvidado incluir en el fichero en inglés el cambio de las líneas 39-40 del español. Por favor, inclúyelo y pide de nuevo una revisión.

2024-06-12 09:43 UTC, tperez-stratio commented on stratio-docs/en/modules/ROOT/pages/installation.adoc
> +** xref:attachment$stratio-eks-policy.json[Descargar permisos permanentes para EKS].
```suggestion
** xref:attachment$stratio-eks-policy.json[Download permanent permissions for EKS].
```

2024-06-12 09:43 UTC, tperez-stratio commented on stratio-docs/en/modules/ROOT/pages/installation.adoc
> +** xref:attachment$stratio-aws-unmanaged-policy.json[Descargar permisos permanentes para AWS no gestionado].
```suggestion
** xref:attachment$stratio-aws-unmanaged-policy.json[Download permanent permissions for AWS unmanaged].
```

2024-06-13 08:32 UTC, tperez-stratio requested changes
@iamjanr te devuelvo un par de cambios y creo que con esto lo tenemos. Gracias!

2024-06-13 08:32 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/installation.adoc
> +En el caso de GKE, además de los permisos anteriores, se necesitarán permisos adicionales para la creación de _clusters_.
```suggestion
En el caso de GKE, además de los permisos anteriores se necesitarán permisos adicionales para la creación de _clusters_.
```

2024-06-13 08:32 UTC, tperez-stratio commented on stratio-docs/en/modules/ROOT/pages/installation.adoc
> +In the case of GKE, in addition to the above permissions, additional permissions will be required for the creation of _clusters_.
```suggestion
In the case of GKE, in addition to the above permissions, additional permissions will be required to create clusters.
```

2024-06-13 09:26 UTC, tperez-stratio approved these changes
LGTM

2024-06-13 09:30 UTC, stg-0 approved these changes
lgtm

2024-06-13 09:30 UTC, merged