[DOC] Documentation of upgrade
Stratio/kind pull request #562
Opened 2024-06-11 14:30 UTC by esierra-stratio

## Description

Upgrade Documentation to Version 0.5.0

## Related Pull Requests

https://github.com/Stratio/kind/pull/558

## Pull Request Checklist:

- [ ] [PR title] Include a title referencing a ticket in Jira (e.g. "[CLOUDS-99] Implement a new funcionality").
- [X] [PR desc] Add a summary of the changes made in simple terms.
- [X] [PR desc] List any pull-request related to this change (docs, tests, feature, etc.).
- [X] [PR labels] Add the corresponding labels (release, skips, cherry-pick, AT-eks-smoke, etc).
- [X] [Docs] Are changes to the documentation required? (if so, please add references to those PRs).
- [ ] [QA] Are new unit tests required according with the changes? (if so, please add references to those PRs).

2024-06-11 14:33 UTC, stratiocommit commented
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/ROOT/pages/quick-start-guide.adoc

2024-06-11 14:37 UTC, stratiocommit commented
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/operations-manual/pages/operations-manual.adoc

2024-06-11 14:56 UTC, stratiocommit commented
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/operations-manual/pages/operations-manual.adoc

2024-06-12 08:00 UTC, tperez-stratio commented
Hola @esierra-stratio, entiendo que falta por añadir el cambio en el archivo en español, ¿lo puedes incluir en la PR por favor? Gracias.

2024-06-12 09:16 UTC, stratiocommit commented
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/operations-manual/pages/operations-manual.adoc

2024-06-13 14:24 UTC, tperez-stratio requested changes
@esierra-stratio te devuelvo las sugerencias de cambio tras mi revisión. Aplícalas si estás conforme y pide de nuevo una revisión. Si tienes cualquier duda, por favor coméntamelo. Una vez tengamos lista la versión en español me pongo con la de inglés. ¡Gracias!

2024-06-13 14:24 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
> +A diferencia de otras versiones del script de _upgrade_, todas las etapas hasta completar la actualización se hace de manera automatizada y sin la interacción humana, excepto para confirmaciones y so
```suggestion
A diferencia de otras versiones del _script_ de _upgrade_, todas las etapas hasta completar la actualización se hacen de manera automatizada y sin interacción humana excepto para confirmaciones y solicitudes de información de versiones. Durante la actualización, es importante tener en cuenta que se realizará un cambio consecutivo de la versión de Kubernetes, siguiendo el procedimiento automatizado que se detalla a continuación:
```

2024-06-13 14:24 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
> +- Actualizar y/o añadir servicios dentro del clúster de kubernetes.
```suggestion
- Actualizar y/o añadir servicios dentro del _cluster_ de Kubernetes.
```

2024-06-13 14:24 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
> +- Actualizar la versión de kubernetes de 1.26.X a 1.27.X.
```suggestion
- Actualizar la versión de Kubernetes de 1.26.X a 1.27.X.
```

2024-06-13 14:24 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
> +- Actualizar la versión de kubernetes de 1.27.X a 1.28.X.
```suggestion
- Actualizar la versión de Kubernetes de 1.27.X a 1.28.X.
```

2024-06-13 14:24 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
> +En cuanto a la actualización de las versiones de kubernetes, ésta se realizará en dos etapas dentro del mismo proceso atómico: primero, el control-plane, y una vez que esté en la nueva versión, los n
```suggestion
En cuanto a la actualización de las versiones de Kubernetes, esta se realizará en dos etapas dentro del mismo proceso atómico: primero, el _control-plane_, y una vez que esté en la nueva versión, los nodos _worker_, iterando por cada grupo de nodos y actualizándolos uno a uno de manera secuencial.
```

2024-06-13 14:24 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
> +CAUTION: La actualización de la versión de kubernetes de los nodos en los clústeres donde no se haya especificado la imagen puede implicar una actualización del sistema operativo.
```suggestion
CAUTION: La actualización de la versión de Kubernetes de los nodos en los _clusters_ donde no se haya especificado la imagen puede implicar una actualización del sistema operativo.
```

2024-06-13 14:24 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
> +  - gcloud (opcional)
¿Esto debe ir en minúscula por necesidad o se pueden poner los nombres legales correctos? Por ejemplo: Google Cloud en vez de gcloud y AWS en lugar de aws.

2024-06-13 14:24 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
> +- Asegurar la compatibilidad de la versión de kubernetes para los diferentes _providers_, con especial atención para clústeres cuyas grupos de nodos no tienen definida una imagen _custom_:
```suggestion
* Se debe asegurar la compatibilidad de la versión de Kubernetes para los diferentes proveedores, con especial atención para _clusters_ cuyos grupos de nodos no tienen definida una imagen _custom_:
```

2024-06-13 14:24 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
> +- Los siguientes binarios deberán estar disponibles en la máquina bastión:
```suggestion
* Los siguientes binarios deberán estar disponibles en la máquina bastión:
```

2024-06-13 14:24 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
> +- Se deberán asegurar los permisos necesarios en el directorio _backup_ de la máquina bastión para que el usuario que ejecuta el _script_ pueda escribir en él (se crea el directorio _./backup/upgrade
```suggestion
* Se deberán asegurar los permisos necesarios en el directorio _backup_ de la máquina bastión para que el usuario que ejecuta el _script_ pueda escribir en él (se crea el directorio _./backup/upgrade/_).
```

2024-06-13 14:24 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
> +  - GCP VMs. No aplica ya que es obligatorio especificar una imagen _custom_.
```suggestion
** EKS:
+
[source,bash]
----
aws eks describe-addon-versions | jq -r ".addons[] | .addonVersions[] | .compatibilities[] | .clusterVersion" | sort -nr | uniq | head -4
----

* AWS VMs:
+
[source,bash]
----
aws ec2 describe-images --filters "Name=name,Values=capa-ami-ubuntu-18.04-*" --query 'Images[*].{ID:ImageId,Name:Name}' --output table
----

* AKS
+
[source,bash]
----
az aks get-versions --location <region> --output table
----
* Azure VMs
+
[source,bash]
----
az vm image list --publisher cncf-upstream --offer "capi" --sku ubuntu-2204  --all -o table
----

* GCP VMs. No aplica ya que es obligatorio especificar una imagen _custom_.
```

2024-06-13 14:24 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
> +- En entornos productivos y especialmente en _providers_ no gestionados, deberá extremarse la precaución. En particular, antes de actualizar, se recomienda hacer un backup de los objetos que gestiona
```suggestion
* En entornos productivos y especialmente en proveedores no gestionados, deberá extremarse la precaución. En particular, antes de actualizar, se recomienda hacer un _backup_ de los objetos que gestionan la infraestructura y de los servicios considerados críticos.
```

2024-06-13 14:24 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
> +Durante la ejecución del script, se requerirá al usuario confirmar la continuación del proceso en diversas etapas y proporcionar información relevante, como la versión de kubernetes que se desea actu
```suggestion
Durante la ejecución del _script_ se requerirá al usuario confirmar la continuación del proceso en diversas etapas y proporcionar información relevante, como la versión de Kubernetes que se desea actualizar.
```

2024-06-13 14:24 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
> +Se debe ejecutar el _script_ _upgrade-provisioner++_++.py_ cuya ayuda se puede consultar con el siguiente comando:
```suggestion
Se debe ejecutar el _script_ `upgrade-provisioner_.py`, cuya ayuda se puede consultar con el siguiente comando:
```

2024-06-13 14:24 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
> +En caso de fallo, al tratarse de un script indempotente, se podrá ejecutar tantas veces como se desea y se obtenga el mensaje de finalización de actualización satisfactoria.
```suggestion
En caso de fallo, al tratarse de un _script_ indempotente, se podrá ejecutar tantas veces como se desea y se obtenga el mensaje de finalización de actualización satisfactoria.
```

2024-06-19 13:58 UTC, esierra-stratio commented on stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
> +  - gcloud (opcional)
aquí convendría dejarlo como está ya que hace referencia a binarios cuyos nombre son los que se reflejan

2024-06-19 14:04 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
> +  - gcloud (opcional)
OK, lo dejamos así entonces.

2024-06-19 20:19 UTC, tperez-stratio approved these changes
LGTM

2024-06-19 20:19 UTC, tperez-stratio commented
Por mi parte OK pero ojo que han salido orphan assets que hay que borrar.

2024-06-20 08:18 UTC, tperez-stratio approved these changes

2024-06-20 08:39 UTC, stg-0 approved these changes
lgtm

2024-06-20 08:39 UTC, merged