[PLT-719] GKE documentation 0.5
Stratio/kind pull request #632
Opened 2024-11-26 12:29 UTC by iamjanr

## Description

Docuemntar GKE 0.5.x

## Related Pull Requests

N/A

## Pull Request Checklist:

- [X] [PR title] Include a title referencing a ticket in Jira (e.g. "[CLOUDS-99] Implement a new funcionality").
- [X] [PR desc] Add a summary of the changes made in simple terms.
- [ ] [PR desc] List any pull-request related to this change (docs, tests, feature, etc.).
- [X] [PR labels] Add the corresponding labels (release, skips, cherry-pick, AT-eks-smoke, etc).
- [ ] [Docs] Are changes to the documentation required? (if so, please add references to those PRs).
- [ ] [QA] Are new unit tests required according with the changes? (if so, please add references to those PRs).

2024-11-28 15:10 UTC, tperez-stratio requested changes
@iamjanr te devuelvo algunas correcciones que he visto. Hay algunas cosas un poco inconexas, así que creo que es mejor esperar a tener la versión final antes de cambiar más cosas. De momento, por favor aplica estos cambios si estás conforme. ¡Gracias!

2024-11-28 15:10 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +* 1 Google Kubernetes Engine (GKE) cluster. (VPC-native).
```suggestion
* 1 _cluster_ de Google Kubernetes Engine (GKE): configurado como VPC-nativa.
```

2024-11-28 15:10 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +* 1 subnet per region.
```suggestion
* 1 subred por región.
```

2024-11-28 15:10 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +** Primary CIDR block for the subnet. (Nodes).
```suggestion
** Bloque CIDR principal para la subred (nodos).
```

2024-11-28 15:10 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +** Secondary CIDR block for the subnet. (Pods & Services).
```suggestion
** Bloque CIDR secundario para la subred (_pods_ y servicios).
```

2024-11-28 15:10 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +* 1 ruta de _peering_. (VPC Network peering).
```suggestion
* 1 ruta de _peering_: conexión mediante _VPC Network peering_.
```

2024-11-28 15:10 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +* 2 rutas, para los  CIDR secundarios de los _pods_ y _services_.
```suggestion
* 2 rutas: para los CIDR secundarios de _pods_ y servicios.
```

2024-11-28 15:10 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +* 5 Reglas de _Firewall_ de VPC (gke-<cluster-name>-<id>-[master, vms, exkubelet, inkubelet, all]).
```suggestion
* 5 Reglas de _firewall_ de VPC: (gke-<nombre-cluster>-<id>-[master, vms, exkubelet, inkubelet, all]).
```

2024-11-28 15:10 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +* Máquinas virtuales para _Workers_ (según descriptor del _cluster_ y autoescalado).
```suggestion
* Máquinas virtuales para _workers_: configuradas según el descriptor del _cluster_ y el autoescalado.
```

2024-11-28 15:10 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +
Se elimina un salto de línea innecesario.
```suggestion
* 1 volumen persistente por máquina virtual.
```

2024-11-28 15:10 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +La red de pods en GKE se configura automáticamente con el CIDR secundario de la red de _pods_ y servicios, que se obtiene de la configuración de la red de VPC al desplegar el _cluster_.
```suggestion
La red de _pods_ en GKE se configura automáticamente con el CIDR secundario para _pods_ y servicios, obtenido de la configuración de la red VPC al desplegar el _cluster_.
```

2024-11-28 15:10 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +La IP asignada al endpoint privado pertencera al rango que se especifica en el descriptor del _cluster_.
```suggestion
En este caso, el _API Server_ se expone únicamente de forma privada, por lo que solo se puede acceder desde la IP asignada al _endpoint_ privado del _cluster_. Esta IP pertenece al rango especificado en el descriptor del _cluster_.
```

2024-11-28 15:10 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/architecture.adoc
> +^|VPC-native
```suggestion
^|VPC-nativa
```

2024-11-28 15:10 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/installation.adoc
> +=== GCP (GKE y no gestionado)
Este título no es correcto, ¿sería "GCP (GKE y _clusters_ no gestionados)"?

2024-11-28 15:10 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/installation.adoc
> +Para GKE, el sistema operativo utilizado por defecto es Container-Optimized OS (COS) y no se deberá indicar ninguna imagen.
```suggestion
Para GKE, el sistema operativo predeterminado es Container-Optimized OS (COS) y no es necesario indicar ninguna imagen específica.
```

2024-12-17 08:39 UTC, iamjanr commented on stratio-docs/es/modules/ROOT/pages/installation.adoc
> +=== GCP (GKE y no gestionado)
Así es como lo tenemos para AWS tb, es decir siempre tenemos AKS por ejemplo para Azure y no gestionado (Para referirnos a Azure con máquinas virtuales), EKS y no gestionado (para referirnos igualmente a máquinas  virtuales en Amazon), si se te ocurre una forma más adecuada comentanoslo y lo vemos

2024-12-18 09:59 UTC, tperez-stratio requested changes
@iamjanr te devuelvo la PR con unos cuantos cambios. Si estás conforme, aplícalos y pide una nueva revisión para aprobar el contenido. Una vez aprobado, me lo llevo a la parte de inglés.

¡Gracias!

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +*** _control_plane_cidr_block_ (master-ipv4-cidr): Es el rango de IP en notación CIDR que se utilizará para la red del _master_. Este rango no debe superponerse con ningún otro rango en uso dentro de
```suggestion
*** _control++_++plane++_++cidr++_++block_ (master-ipv4-cidr) (obligatorio): es el rango de IP en notación CIDR que se utilizará para la red del _master_. Este rango no debe superponerse con ningún otro rango en uso dentro de la red del _cluster_. Se aplica cuando _enabled++_++private++_++nodes_ es "true" y debe ser una subred /28.
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +* ip_allocation_policy: Representa las opciones de configuración para la asignación de IP del clúster GKE. (Si no se especifica, se usarán los valores predeterminados de GKE).
```suggestion
* ip++_++allocation++_++policy: representa las opciones de configuración para la asignación de IP del _cluster_ GKE (si no se especifica, se usarán los valores predeterminados de GKE).
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +** cluster_ipv4_cidr_block: Representa el rango de direcciones IP para las IP de los pods del clúster GKE. (Si no se especifica, se elegirá el rango con el tamaño predeterminado).
```suggestion
** cluster++_++ipv4++_++cidr++_++block: representa el rango de direcciones IP para las IP de los _pods_ del _cluster_ GKE (si no se especifica, se elegirá el rango con el tamaño predeterminado).
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +** services_ipv4_cidr_block: Representa el rango de direcciones IP para las IP de los servicios del clúster GKE. (Si no se especifica, se elegirá el rango con el tamaño predeterminado).
```suggestion
** services++_++ipv4++_++cidr++_++block: representa el rango de direcciones IP para las IP de los servicios del _cluster_ GKE (si no se especifica, se elegirá el rango con el tamaño predeterminado).
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +** cluster_secondary_range_name: Representa el nombre del rango secundario que se utilizará para el bloque CIDR del clúster GKE. El rango se utilizará para las direcciones IP de los pods y debe ser u
```suggestion
** cluster++_++secondary++_++range++_++name: representa el nombre del rango secundario que se utilizará para el bloque CIDR del _cluster_ GKE. El rango se utilizará para las direcciones IP de los _pods_ y debe ser un rango secundario existente asociado con la subred del _cluster_.
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +** services_secondary_range_name: Representa el nombre del rango secundario que se utilizará para el bloque CIDR de los servicios. El rango se utilizará para las IP de los servicios y debe ser un ran
```suggestion
** services++_++secondary++_++range++_++name: representa el nombre del rango secundario que se utilizará para el bloque CIDR de los servicios. El rango se utilizará para las IP de los servicios y debe ser un rango secundario existente asociado con la subred del _cluster_.
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +* _master_authorized_networks_config_: Representa la configuración de redes autorizadas del clúster.
```suggestion
* _master++_++authorized++_++networks++_++config_: representa la configuración de redes autorizadas del _cluster_.
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +NOTE: Al habilitar la configuración de redes autorizadas, se impedirá que todo el tráfico externo acceda al _master_ de kubernetes a través de HTTPS, excepto el tráfico de los bloques de CIDR especif
```suggestion
NOTE: Al habilitar la configuración de redes autorizadas, se impedirá que todo el tráfico externo acceda al _master_ de Kubernetes a través de HTTPS excepto el tráfico de los bloques de CIDR especificados, las IP públicas de Google Compute Engine y las IP de los servicios de Google Cloud.
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +** _cidr_blocks_: Lista de bloques CIDR que se permiten acceder al _master_. (Opcional ya que gcp_public_cidrs_access_enabled es siempre true)
```suggestion
** _cidr++_++blocks_ (opcional, ya que gcp++_++public++_++cidrs++_++access++_++enabled es siempre "true"): lista de bloques CIDR que se permiten acceder al _master_.
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +*** _cidr_block_: Rango de IP en notación CIDR que se permitirá acceder al _master_. (Obligatorio en el caso de que _cidr_blocks_ esté presente)
```suggestion
*** _cidr++_++block_ (obligatorio en el caso de que _cidr++_++blocks_ esté presente): rango de IP en notación CIDR que se permitirá acceder al _master_.
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +*** _display_name_: Nombre de la red autorizada. (Opcional)
```suggestion
*** _display++_++name_ (opcional): nombre de la red autorizada.
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +** _gcp_public_cidrs_access_enabled_: Indica si se permite el acceso a las direcciones IP públicas de Google Compute Engine. (Obligatorio: false, si _enable_private_endpoint es true)(Default: false)
```suggestion
** _gcp++_++public++_++cidrs++_++access++_++enabled_ (obligatorio: "false", si _enable++_++private++_++endpoint es "true") (default: false): indica si se permite el acceso a las direcciones IP públicas de Google Compute Engine.
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +* _monitoring_config_: Define la monitorización del cluster.
```suggestion
* _monitoring++_++config_: define la monitorización del _cluster_.
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +** _enable_managed_prometheus_: Habilita la monitorización gestionada del cluster con Prometheus. (Obligatorio)(Default: false)
```suggestion
** _enable++_++managed++_++prometheus_ (obligatorio) (default: false): habilita la monitorización gestionada del _cluster_ con Prometheus.
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +* _logging_config_: Define la configuración de _logging_ del cluster.
```suggestion
* _logging++_++config_: define la configuración de _logging_ del _cluster_.
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +** _system_components_: Habilita el componente _system_ de _logging_. (Obligatorio)(Default: false)
```suggestion
** _system++_++components_ (obligatorio) (default: false): habilita el componente _system_ de _logging_.
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +** _workloads_: Habilita el componente _workloads_ de _logging_. (Obligatorio)(Default: false)
```suggestion
** _workloads_ (obligatorio) (default: false): habilita el componente _workloads_ de _logging_.
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +NOTE: Cualquier modificaciónde los parámetros anteriormente mencionados no tendrá efecto, sólo se aplican en tiempo de creación del cluster.
```suggestion
NOTE: Cualquier modificación de los parámetros anteriormente mencionados no tendrá efecto, sólo se aplican en tiempo de creación del _cluster_. 
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +* _taints_: taints de los nodos en Kubernetes (opcional).
```suggestion
* _taints_: _taints_ de los nodos en Kubernetes (opcional).
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +* _az_: zona del grupo de _workers_ (opcional). En caso de especificarse, solamente se utilizará ésta para todo el grupo. Este parámetro invalida lo especificado en _zone++_++distribution_.
```suggestion
* _az_: zona del grupo de _workers_ (opcional). En caso de especificarse, solamente se utilizará esta para todo el grupo. Este parámetro invalida lo especificado en _zone++_++distribution_.
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +* En caso de utilizar una infraestructura personalizada, se deberá indicar la VPC y la subnet de la región.
```suggestion
* En caso de utilizar una infraestructura personalizada, se deberá indicar la VPC y la subred de la región.
+
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +* La versión de Kubernetes ha de ser (1.28) y ha de estar soportada por GKE.
```suggestion
* La versión de Kubernetes debe ser (1.28) y estar soportada por GKE.
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +Esta fase (aprovisionamiento e instalación de Kubernetes) deberá ejecutarse desde la máquina bastíon.
```suggestion
Esta fase (aprovisionamiento e instalación de Kubernetes) deberá ejecutarse desde la máquina bastión.
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +2. Stratio KEOS documentation
```suggestion
1. Post-installation Stratio cloud-provisioner documentation.
2. Stratio KEOS documentation.
```

2024-12-18 09:59 UTC, tperez-stratio commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +NOTE: Si los rangos de IP ya están creados, se deben usar los nombres especificados (services_secondary_range_name y cluster_secondary_range_name). Si no existen, se debe usar la notación CIDR (servi
```suggestion
NOTE: Si los rangos de IP ya están creados, se deben usar los nombres especificados (services++_++secondary++_++range++_++name y cluster++_++secondary++_++range++_++name). Si no existen, se debe usar la notación CIDR (services++_++ipv4++_++cidr++_++block y cluster++_++ipv4++_++cidr++_++block) para crearlos, pero no se pueden usar ambos métodos simultáneamente.
```

2024-12-18 10:14 UTC, iamjanr commented on stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> +NOTE: Crear un bastión para proceder a la instalación.
Lo he cambiado a TIP, gracias por el comentario

2024-12-19 10:41 UTC, tperez-stratio approved these changes
LGTM

2024-12-19 12:06 UTC, lrios-stratio approved these changes

2024-12-19 12:06 UTC, merged