Added script upgrade from 0.5 to 0.6. OK EKS
Stratio/kind pull request #643
Opened 2024-12-12 16:48 UTC by lreciomelero

## Description

_Please add the PR description here._

## Related Pull Requests

- _PR number_: _brief description (e.g. "documentation")_
- _PR number_: _brief description (e.g. "tests enhancements")_

## Pull Request Checklist:

- [ ] [PR title] Include a title referencing a ticket in Jira (e.g. "[CLOUDS-99] Implement a new funcionality").
- [ ] [PR desc] Add a summary of the changes made in simple terms.
- [ ] [PR desc] List any pull-request related to this change (docs, tests, feature, etc.).
- [ ] [PR labels] Add the corresponding labels (release, skips, cherry-pick, AT-eks-smoke, etc).
- [ ] [Docs] Are changes to the documentation required? (if so, please add references to those PRs).
- [ ] [QA] Are new unit tests required according with the changes? (if so, please add references to those PRs).

2025-01-20 14:29 UTC, tperez-stratio requested changes
@lreciomelero te devuelvo cambios en la parte de español. Aplica si estás conforme y pide una nueva revisión para llevármelos a la de inglés. ¡Gracias!

2025-01-20 14:29 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +| -k, --kubeconfig             | Especifica el archivo de configuración de kubectl a utilizar.                    | ~/.kube/config               | No
```suggestion
| -k, --kubeconfig | Especifica el archivo de configuración de Kubectl a utilizar. | ~/.kube/config | No
```

2025-01-20 14:29 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +| --enable-lb-controller       | Instala el controlador de balanceador de carga en clústeres de EKS (desactivado por defecto). | False                        | No
```suggestion
| --enable-lb-controller | Activa el controlador de balanceador de carga en EKS (desactivado por defecto). | False | No
```

2025-01-20 14:29 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +| --disable-prepare-capsule    | Deshabilita la preparación del entorno para el proceso de actualización.          | False                        | No
```suggestion
| --disable-prepare-capsule | Desactiva la preparación del entorno para el proceso de actualización. | False  | No
```

2025-01-20 14:29 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +*Para EKS en AWS:*
```suggestion
*Ejemplos:*

* EKS en AWS:
```

2025-01-20 14:29 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +[source,bash]
```suggestion
+
[source,bash]
```

2025-01-20 14:29 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +[source,bash]
```suggestion
* Azure VMs:
+
[source,bash]
```

2025-01-20 14:29 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +.Obtener User Assign Identity
```suggestion
.Obtener `user-assign-identity` en Azure
```

2025-01-20 14:29 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +Para obtener el user assign identity que se debe indicar es posible recurrir al cli de azure:
```suggestion
Para obtener el `user-assign-identity` es posible recurrir al CLI de Azure:
```

2025-01-20 14:29 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +====
```suggestion
----

====
```

2025-01-20 14:29 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +== Directorios necesarios
```suggestion
== Estructura necesaria
```

2025-01-20 14:29 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +El directorio de trabajo debe contener:
```suggestion
Asegúrate de que el directorio de trabajo incluya:
```

2025-01-20 14:29 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +- `upgrade-provisioner.py` (el script principal)
```suggestion
* `upgrade-provisioner.py`: _script_ principal.
```

2025-01-20 14:29 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +- `templates/` (directorio con plantillas Jinja2 requeridas)
```suggestion
* `templates/`: plantillas Jinja2.
```

2025-01-20 14:29 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +- `files/` (archivos adicionales, como configuraciones para Helm)
```suggestion
* `files/`: archivos adicionales (configuraciones, Helm, etc.).
```

2025-01-20 14:29 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +- `requirements.txt` (archivo con las dependencias necesarias)
```suggestion
* `requirements.txt`: dependencias necesarias.
```

2025-01-20 14:29 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +- `secrets.yml` (archivo con las credenciales del cluster)
```suggestion
* `secrets.yml`: credenciales del _cluster_.
```

2025-01-20 14:29 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +- `.aws/` (solo en EKS. Directorio con los archivos de configuración de aws)
```suggestion
* `.aws/`: archivos de configuración de AWS (solo para EKS).
```

2025-01-20 14:29 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +- `.kube/`  (directorio con el kubeconfig)
```suggestion
* `.kube/`: directorio con el archivo _kubeconfig_.
```

2025-01-20 16:22 UTC, lreciomelero commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> += Upgrade Provisioner Script
Que te parece: Script de upgrade de cloud provisioner? Cloud provisioner es una herramienta propia de Stratio y creo que es más correcto llamarlo así que aprovisionador. Por otro lado, actualización no me convence al ser un proceso de upgrade y no de update. Si el destino es para una documentación técnica creo que es mas correcto dejarlo así.

2025-01-20 16:28 UTC, lreciomelero commented on stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
Está aplicado!

2025-01-20 16:37 UTC, lreciomelero commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +Es necesario ejecutar el contenedor Docker utilizando la imagen de upgrade. En él dispondremos del script y del resto de archivos necesarios para ejecutar el proceso:
Creo  que es mejor que para hacer referencia a la actualización, sea mediante la palabra upgrade: Ejecuta el contenedor Docker con la imagen de _upgrade_ , montando los archivos necesarios:

2025-01-20 16:44 UTC, lreciomelero commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +=== Script de Upgrade
=== Uso del _script_ de _upgrade_

2025-01-20 21:23 UTC, tperez-stratio requested changes
@lreciomelero he cogido la PR de vuelta pensando que habías terminado de aplicar cambios pero luego he visto que no y que aún quedan pendientes. No obstante te envío respuesta a los comentarios que habías dejado. Por favor, pide una nueva revisión cuando termines de verlo todo. ¡Gracias!

2025-01-20 21:23 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> += Upgrade Provisioner Script
Pues te compro lo de aprovisionador por Cloud Provisioner, porque como dices, es el nombre del componente. De hecho, lo correcto sería "_Script_ de actualización de _Stratio Cloud Provisioner_", pero estando en la documentación de Stratio Cloud Provisioner creo que no es necesario repetir esto, por lo que lo dejaría en "_Script_ de actualización". 

Lo que no veo es dejar "upgrade", que es una palabra en inglés que tiene traducción y por ello siempre la utilizamos en la documentación de manera traducida. A veces se traduce por actualización a secas y otra por actualización de versión. ¿Cómo lo ves?

"_Script_ de actualización de versión"

2025-01-20 21:23 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +Es necesario ejecutar el contenedor Docker utilizando la imagen de upgrade. En él dispondremos del script y del resto de archivos necesarios para ejecutar el proceso:
Remito al comentario anterior, no sería correcto utilizar la palabra en inglés cuando se puede traducir, a no ser que sea el nombre de algo y vaya en inglés... ¿si ponemos "la imagen de actualización de versión" lo ves mejor?

2025-01-20 21:23 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +=== Script de Upgrade
Mismo comentario.

2025-01-21 08:49 UTC, lreciomelero commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> += Upgrade Provisioner Script
vale, pues así entonces!

2025-01-21 08:50 UTC, lreciomelero commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +Es necesario ejecutar el contenedor Docker utilizando la imagen de upgrade. En él dispondremos del script y del resto de archivos necesarios para ejecutar el proceso:
vale

2025-01-22 14:16 UTC, tperez-stratio requested changes
@lreciomelero te paso los últimos cambios y he añadido en un commit la versión en inglés. Aplica si estás conforme y pide una última revisión para aprobación. ¡Gracias!

2025-01-22 14:16 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +El `kubeconfig` generado por defecto en EKS tiene un _token_ con tiempo de vida limitado. Para evitar interrupciones, genera un `kubeconfig` actualizado con:
```suggestion
El `kubeconfig` generado por defecto en EKS tiene un _token_ con tiempo de vida limitado. Para evitar interrupciones, puedes generar un `kubeconfig` actualizado con:
```

2025-01-22 14:16 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +| -y, --yes                    | No requiere confirmación entre tareas (modo automático).                         | False                        | No
```suggestion
| `-y`, `--yes` | No requiere confirmación entre tareas (modo automático). | False | No 
```

2025-01-22 14:16 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +| -k, --kubeconfig | Especifica el archivo de configuración de Kubectl a utilizar. | ~/.kube/config | No
```suggestion
| `-k`, `--kubeconfig` | Especifica el archivo de configuración de Kubectl a utilizar. | ~/.kube/config | No
```

2025-01-22 14:16 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +| -p, --vault-password | Archivo con la contraseña del Vault necesaria para descifrar secretos. | | Sí
```suggestion
| `-p`, `--vault-password` | Archivo con la contraseña del Vault necesaria para descifrar secretos. | | Sí
```

2025-01-22 14:16 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +| -s, --secrets | Archivo de secretos cifrados. | secrets.yml | No
```suggestion
| `-s`, `--secrets` | Archivo de secretos cifrados. | secrets.yml | No
```

2025-01-22 14:16 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +| -i, --user-assign-identity | ID asignado al usuario en Azure (_clientID_ de `nodes_identity`). |  | Sí (Azure)
```suggestion
| `-i`, `--user-assign-identity` | ID asignado al usuario en Azure (_clientID_ de `nodes_identity`). |  | Sí (Azure)
```

2025-01-22 14:16 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +| --enable-lb-controller | Activa el controlador de balanceador de carga en EKS (desactivado por defecto). | False | No
```suggestion
| `--enable-lb-controller` | Activa el controlador de balanceador de carga en EKS (desactivado por defecto). | False | No
```

2025-01-22 14:16 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +| --disable-backup | Desactiva el respaldo antes de actualizar (habilitado por defecto). | False | No
```suggestion
| `--disable-backup` | Desactiva el respaldo antes de actualizar (habilitado por defecto). | False | No
```

2025-01-22 14:16 UTC, tperez-stratio commented on stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> +| --disable-prepare-capsule | Desactiva la preparación del entorno para el proceso de actualización. | False  | No
```suggestion
| `--disable-prepare-capsule` | Desactiva la preparación del entorno para el proceso de actualización. | False  | No
```

2025-01-23 08:19 UTC, merged